### ISSUE TITLE
crash: unable to run hostnamectl

### ISSUE THREAD

**Issue by jbicha** [ubuntu/gnome-info-collect#1]
I built this snap using snapcraft from the edge channel (rev. 8122).

```
$ snap run gnome-info-collect
Traceback (most recent call last):
  File "/snap/gnome-info-collect/x1/usr/bin/gnome-info-collect", line 445, in <module>
    main()
  File "/snap/gnome-info-collect/x1/usr/bin/gnome-info-collect", line 425, in main
    output = GCollector().collect_data()
  File "/snap/gnome-info-collect/x1/usr/bin/gnome-info-collect", line 53, in collect_data
    self._get_hw_os_info()
  File "/snap/gnome-info-collect/x1/usr/bin/gnome-info-collect", line 69, in _get_hw_os_info
    hw_os_info = subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'hostnamectl' returned non-zero exit status 127.
```

**Comment by jbicha** [comment]
@kenvandine I confirm that the snap works for me now on Ubuntu 22.10.
